import { CATEGORY_IDS } from "./lib.mjs";

/**
 * Static venue definitions (deterministic). Ratings/prices finalized in seed.mjs via RNG.
 * @typedef {object} VenueDef
 */

/** @type {VenueDef[]} */
export const VENUE_DEFINITIONS = [
  {
    slug: "anatolian-flame-grill",
    seedOffset: 0,
    photoPool: "restaurant",
    categoryId: CATEGORY_IDS.restaurants,
    listingType: "featured",
    city: "Istanbul, Turkey",
    address: "Caferağa Mah., Moda Cd. No: 42, Kadıköy, 34710 Istanbul",
    latitude: 40.9872,
    longitude: 29.0274,
    phone: "+90 216 555 0142",
    contact_whatsapp: "+902165550142",
    ratingBase: 4.7,
    bookingPriceBase: 48,
    name: {
      en: "Anatolian Flame Grill",
      ru: "Гриль «Анатолийское пламя»",
      es: "Parrilla Llama Anatolia",
      pt: "Grelha Chama Anatólia",
      fr: "Grill Flamme Anatolienne",
      de: "Anatolian Flame Grill",
    },
    description: {
      en: "Wood-fired meze and Aegean seafood on a terrace overlooking the Marmara. Reserve for sunset tasting menus.",
      ru: "Мезе на дровах и эгейские морепродукты на террасе с видом на Мраморное море. Бронируйте дегустационное меню на закате.",
      es: "Meze al fuego de leña y marisco del Egeo en una terraza con vistas al Marmara. Reserva menús degustación al atardecer.",
      pt: "Meze na lenha e marisco do Egeu num terraço com vista para o Mármara. Reserve menus de degustação ao pôr do sol.",
      fr: "Mezze au feu de bois et fruits de mer égéens sur une terrasse vue Marmara. Réservez les menus dégustation au coucher du soleil.",
      de: "Holzgefeuerte Meze und Ägäis-Meeresfrüchte auf der Terrasse mit Marmarameer-Blick. Reservieren Sie Sunset-Degustationsmenüs.",
    },
    tags: {
      en: ["restaurant", "istanbul", "seafood", "terrace", "fine dining"],
      ru: ["ресторан", "стамбул", "морепродукты", "терраса", "гастрономия"],
      es: ["restaurante", "estambul", "mariscos", "terraza", "alta cocina"],
      pt: ["restaurante", "istambul", "marisco", "terraço", "alta gastronomia"],
      fr: ["restaurant", "istanbul", "fruits de mer", "terrasse", "gastronomie"],
      de: ["restaurant", "istanbul", "meeresfrüchte", "terrasse", "feinschmecker"],
    },
  },
  {
    slug: "barraca-verde-cafe",
    seedOffset: 7,
    photoPool: "cafe",
    categoryId: CATEGORY_IDS.restaurants,
    listingType: "recommended",
    city: "Barcelona, Spain",
    address: "Carrer de Blai 88, 08004 Barcelona",
    latitude: 41.3748,
    longitude: 2.1692,
    phone: "+34 93 555 7821",
    contact_whatsapp: "+34935557821",
    ratingBase: 4.5,
    bookingPriceBase: 22,
    name: {
      en: "Barraca Verde Café",
      ru: "Кафе Barraca Verde",
      es: "Café Barraca Verde",
      pt: "Café Barraca Verde",
      fr: "Café Barraca Verde",
      de: "Barraca Verde Café",
    },
    description: {
      en: "Specialty flat whites, Catalan pastries, and laptop-friendly tables near Parc de la Ciutadella.",
      ru: "Авторский флэт уайт, каталонская выпечка и столы для ноутбуков рядом с парком Сьюдаделя.",
      es: "Flat whites de especialidad, bollería catalana y mesas para portátiles junto al Parc de la Ciutadella.",
      pt: "Flat whites de especialidade, pastelaria catalã e mesas para portáteis perto do Parc de la Ciutadella.",
      fr: "Flat whites de spécialité, pâtisseries catalanes et tables nomades près du Parc de la Ciutadella.",
      de: "Spezialitäten-Flat-Whites, katalanisches Gebäck und Laptop-Tische am Parc de la Ciutadella.",
    },
    tags: {
      en: ["cafe", "barcelona", "specialty coffee", "pastries", "coworking friendly"],
      ru: ["кафе", "барселона", "спешиалти", "выпечка", "для работы"],
      es: ["café", "barcelona", "café de especialidad", "bollería", "para trabajar"],
      pt: ["café", "barcelona", "café especial", "pastelaria", "para trabalhar"],
      fr: ["café", "barcelone", "café de spécialité", "pâtisseries", "travail"],
      de: ["café", "barcelona", "spezialitätenkaffee", "gebäck", "arbeiten"],
    },
  },
  {
    slug: "spree-side-taproom",
    seedOffset: 14,
    photoPool: "bar",
    categoryId: CATEGORY_IDS.bars,
    listingType: "featured",
    city: "Berlin, Germany",
    address: "Schlesische Str. 26, 10997 Berlin",
    latitude: 52.5003,
    longitude: 13.4442,
    phone: "+49 30 5559 3310",
    contact_whatsapp: "+493055593310",
    ratingBase: 4.6,
    bookingPriceBase: 35,
    name: {
      en: "Spree Side Taproom",
      ru: "Паб Spree Side Taproom",
      es: "Cervecería Spree Side Taproom",
      pt: "Cervejaria Spree Side Taproom",
      fr: "Brasserie Spree Side Taproom",
      de: "Spree Side Taproom",
    },
    description: {
      en: "Craft lagers, Berliner Weisse cocktails, and vinyl nights two blocks from the Spree in Kreuzberg.",
      ru: "Крафтовые лагеры, коктейли на берлинер вайсе и виниловые вечера в двух кварталах от Шпрее в Кройцберге.",
      es: "Lagers artesanales, cócteles Berliner Weisse y noches de vinilo a dos manzanas del Spree en Kreuzberg.",
      pt: "Lagers artesanais, cocktails Berliner Weisse e noites de vinil a dois quarteirões do Spree em Kreuzberg.",
      fr: "Lagers artisanales, cocktails Berliner Weisse et soirées vinyles à deux rues de la Spree à Kreuzberg.",
      de: "Craft-Lager, Berliner-Weisse-Cocktails und Vinyl-Nächte zwei Blocks von der Spree in Kreuzberg.",
    },
    tags: {
      en: ["bar", "berlin", "craft beer", "cocktails", "live music"],
      ru: ["бар", "берлин", "крафт", "коктейли", "музыка"],
      es: ["bar", "berlín", "cerveza artesanal", "cócteles", "música en vivo"],
      pt: ["bar", "berlim", "cerveja artesanal", "cocktails", "música ao vivo"],
      fr: ["bar", "berlin", "bière artisanale", "cocktails", "musique live"],
      de: ["bar", "berlin", "craft beer", "cocktails", "live musik"],
    },
  },
  {
    slug: "marina-crown-suites",
    seedOffset: 21,
    photoPool: "hotel",
    categoryId: CATEGORY_IDS.hotels,
    listingType: "featured",
    city: "Dubai, UAE",
    address: "Dubai Marina Walk, Tower 3, Level 12, Dubai",
    latitude: 25.0805,
    longitude: 55.1403,
    phone: "+971 4 555 9021",
    contact_whatsapp: "+97145559021",
    ratingBase: 4.8,
    bookingPriceBase: 210,
    name: {
      en: "Marina Crown Suites",
      ru: "Отель Marina Crown Suites",
      es: "Marina Crown Suites",
      pt: "Marina Crown Suites",
      fr: "Marina Crown Suites",
      de: "Marina Crown Suites",
    },
    description: {
      en: "Boutique marina suites with infinity pool, concierge, and late checkout for Red Sea weekenders.",
      ru: "Бутик-люксы у марины с инфинити-бассейном, консьержем и поздним выездом для уик-энда.",
      es: "Suites boutique en la marina con piscina infinita, conserjería y late checkout para escapadas.",
      pt: "Suítes boutique na marina com piscina infinita, concierge e late checkout para escapadas.",
      fr: "Suites boutique marina, piscine à débordement, conciergerie et départ tardif pour escapades.",
      de: "Boutique-Marina-Suiten mit Infinity-Pool, Concierge und Late Checkout für Wochenendtrips.",
    },
    tags: {
      en: ["hotel", "dubai", "marina", "pool", "luxury"],
      ru: ["отель", "дубай", "марина", "бассейн", "люкс"],
      es: ["hotel", "dubái", "marina", "piscina", "lujo"],
      pt: ["hotel", "dubai", "marina", "piscina", "luxo"],
      fr: ["hôtel", "dubaï", "marina", "piscine", "luxe"],
      de: ["hotel", "dubai", "marina", "pool", "luxus"],
    },
  },
  {
    slug: "thames-core-fitness",
    seedOffset: 28,
    photoPool: "gym",
    categoryId: CATEGORY_IDS.fitness,
    listingType: "recommended",
    city: "London, UK",
    address: "12 Southwark St, London SE1 1TJ",
    latitude: 51.5055,
    longitude: -0.0953,
    phone: "+44 20 7946 0822",
    contact_whatsapp: "+442079460822",
    ratingBase: 4.4,
    bookingPriceBase: 18,
    name: {
      en: "Thames Core Fitness",
      ru: "Фитнес Thames Core",
      es: "Thames Core Fitness",
      pt: "Thames Core Fitness",
      fr: "Thames Core Fitness",
      de: "Thames Core Fitness",
    },
    description: {
      en: "Boutique gym with HYROX zone, reformer pilates, and 24/7 access near London Bridge.",
      ru: "Бутик-зал с зоной HYROX, реформер-пилатесом и доступом 24/7 у London Bridge.",
      es: "Gimnasio boutique con zona HYROX, pilates reformer y acceso 24/7 cerca de London Bridge.",
      pt: "Ginásio boutique com zona HYROX, pilates reformer e acesso 24/7 perto de London Bridge.",
      fr: "Salle boutique avec zone HYROX, pilates reformer et accès 24/7 près de London Bridge.",
      de: "Boutique-Gym mit HYROX-Zone, Reformer-Pilates und 24/7-Zugang nahe London Bridge.",
    },
    tags: {
      en: ["gym", "london", "hyrox", "pilates", "24/7"],
      ru: ["зал", "лондон", "hyrox", "пилатес", "круглосуточно"],
      es: ["gimnasio", "londres", "hyrox", "pilates", "24 horas"],
      pt: ["ginásio", "londres", "hyrox", "pilates", "24 horas"],
      fr: ["salle de sport", "londres", "hyrox", "pilates", "24h/24"],
      de: ["fitnessstudio", "london", "hyrox", "pilates", "24/7"],
    },
  },
  {
    slug: "atelier-rose-beaute",
    seedOffset: 35,
    photoPool: "beauty",
    categoryId: CATEGORY_IDS.beauty,
    listingType: "recommended",
    city: "Paris, France",
    address: "14 Rue des Francs-Bourgeois, 75004 Paris",
    latitude: 48.8573,
    longitude: 2.3594,
    phone: "+33 1 55 55 41 20",
    contact_whatsapp: "+33155554120",
    ratingBase: 4.9,
    bookingPriceBase: 75,
    name: {
      en: "Atelier Rose Beauté",
      ru: "Салон Atelier Rose Beauté",
      es: "Atelier Rose Beauté",
      pt: "Atelier Rose Beauté",
      fr: "Atelier Rose Beauté",
      de: "Atelier Rose Beauté",
    },
    description: {
      en: "French skincare studio offering biologique facials, brow lamination, and bridal packages in Le Marais.",
      ru: "Студия ухода с биологическими фейсами, ламинированием бровей и пакетами для невест в Маре.",
      es: "Estudio de cuidado facial con tratamientos biológicos, laminado de cejas y packs nupciales en Le Marais.",
      pt: "Estúdio de skincare com faciais biológicos, laminação de sobrancelhas e packs de noiva no Marais.",
      fr: "Studio soin visage bio, brow lamination et forfaits mariée dans le Marais.",
      de: "Skincare-Studio mit biologischen Facials, Brow-Lamination und Braut-Paketen im Marais.",
    },
    tags: {
      en: ["beauty salon", "paris", "skincare", "brows", "bridal"],
      ru: ["салон", "париж", "уход", "брови", "невеста"],
      es: ["salón de belleza", "parís", "skincare", "cejas", "novias"],
      pt: ["salão de beleza", "paris", "skincare", "sobrancelhas", "noivas"],
      fr: ["institut de beauté", "paris", "soin visage", "sourcils", "mariée"],
      de: ["beauty salon", "paris", "hautpflege", "augenbrauen", "braut"],
    },
  },
  {
    slug: "lx-factory-hub",
    seedOffset: 42,
    photoPool: "coworking",
    categoryId: CATEGORY_IDS.entertainment,
    listingType: "recommended",
    city: "Lisbon, Portugal",
    address: "Rua Rodrigues de Faria 103, 1300-501 Lisboa",
    latitude: 38.7038,
    longitude: -9.1782,
    phone: "+351 21 555 6634",
    contact_whatsapp: "+351215556634",
    ratingBase: 4.5,
    bookingPriceBase: 28,
    name: {
      en: "LX Factory Hub",
      ru: "Коворкинг LX Factory Hub",
      es: "LX Factory Hub",
      pt: "LX Factory Hub",
      fr: "LX Factory Hub",
      de: "LX Factory Hub",
    },
    description: {
      en: "Day passes with fiber Wi‑Fi, podcast booths, and rooftop espresso bar inside LX Factory.",
      ru: "Дневные абонементы с оптикой, подкаст-кабинами и кофе на крыше в LX Factory.",
      es: "Pases diarios con fibra, cabinas de podcast y café en la azotea dentro de LX Factory.",
      pt: "Passes diários com fibra, cabines de podcast e café no rooftop no LX Factory.",
      fr: "Pass journée fibre optique, cabines podcast et café rooftop au LX Factory.",
      de: "Tagespässe mit Glasfaser, Podcast-Booths und Rooftop-Espresso in der LX Factory.",
    },
    tags: {
      en: ["coworking", "lisbon", "wifi", "rooftop", "networking"],
      ru: ["коворкинг", "лиссабон", "wifi", "крыша", "нетворкинг"],
      es: ["coworking", "lisboa", "wifi", "azotea", "networking"],
      pt: ["coworking", "lisboa", "wifi", "rooftop", "networking"],
      fr: ["coworking", "lisbonne", "wifi", "toit-terrasse", "networking"],
      de: ["coworking", "lissabon", "wlan", "dachterrasse", "networking"],
    },
  },
  {
    slug: "ocean-drive-night-society",
    seedOffset: 49,
    photoPool: "club",
    categoryId: CATEGORY_IDS.clubs,
    listingType: "featured",
    city: "Miami, USA",
    address: "1450 Ocean Dr, Miami Beach, FL 33139",
    latitude: 25.782,
    longitude: -80.13,
    phone: "+1 305 555 4410",
    contact_whatsapp: "+13055554410",
    ratingBase: 4.3,
    bookingPriceBase: 95,
    name: {
      en: "Ocean Drive Night Society",
      ru: "Клуб Ocean Drive Night Society",
      es: "Ocean Drive Night Society",
      pt: "Ocean Drive Night Society",
      fr: "Ocean Drive Night Society",
      de: "Ocean Drive Night Society",
    },
    description: {
      en: "South Beach nightclub with resident DJs, VIP tables, and sunrise terrace after-parties.",
      ru: "Ночной клуб на South Beach с резидентами, VIP-столами и террасой для афтепати на рассвете.",
      es: "Club nocturno en South Beach con DJs residentes, mesas VIP y terraza para afters al amanecer.",
      pt: "Clube noturno em South Beach com DJs residentes, mesas VIP e terraço para afters ao nascer do sol.",
      fr: "Club nocturne South Beach, DJs résidents, tables VIP et terrasse after au lever du soleil.",
      de: "South-Beach-Club mit Resident-DJs, VIP-Tischen und Sunrise-Terrasse für Afterpartys.",
    },
    tags: {
      en: ["night club", "miami", "dj", "vip", "rooftop"],
      ru: ["клуб", "майами", "dj", "vip", "терраса"],
      es: ["discoteca", "miami", "dj", "vip", "terraza"],
      pt: ["clube noturno", "miami", "dj", "vip", "rooftop"],
      fr: ["boîte de nuit", "miami", "dj", "vip", "terrasse"],
      de: ["nachtclub", "miami", "dj", "vip", "dachterrasse"],
    },
  },
  {
    slug: "nevsky-smoke-lounge",
    seedOffset: 56,
    photoPool: "hookah",
    categoryId: CATEGORY_IDS.bars,
    listingType: "recommended",
    city: "Moscow, Russia",
    address: "Kuznetsky Most 7, Bldg 1, 107031 Moscow",
    latitude: 55.7614,
    longitude: 37.6245,
    phone: "+7 495 555 7788",
    contact_whatsapp: "+74955557788",
    ratingBase: 4.6,
    bookingPriceBase: 40,
    name: {
      en: "Nevsky Smoke Lounge",
      ru: "Кальянная Nevsky Smoke Lounge",
      es: "Nevsky Smoke Lounge",
      pt: "Nevsky Smoke Lounge",
      fr: "Nevsky Smoke Lounge",
      de: "Nevsky Smoke Lounge",
    },
    description: {
      en: "Premium hookah lounge with fruit bowls, tea pairings, and quiet booths off Kuznetsky Most.",
      ru: "Премиальная кальянная с фруктовыми чашами, чайными парами и тихими кабинами у Кузнецкого моста.",
      es: "Lounge de cachimba premium con bowls de fruta, maridajes de té y reservados tranquilos en Kuznetsky Most.",
      pt: "Lounge de shisha premium com bowls de fruta, chás harmonizados e cabines tranquilas no Kuznetsky Most.",
      fr: "Lounge chicha premium, bowls fruités, accords thé et alcôves calmes près du Kuznetsky Most.",
      de: "Premium-Shisha-Lounge mit Fruchtköpfen, Tee-Pairings und ruhigen Boxen an der Kuznetsky Most.",
    },
    tags: {
      en: ["hookah lounge", "moscow", "shisha", "tea", "lounge"],
      ru: ["кальянная", "москва", "кальян", "чай", "лаунж"],
      es: ["salón de cachimbas", "moscú", "shisha", "té", "lounge"],
      pt: ["lounge de shisha", "moscovo", "shisha", "chá", "lounge"],
      fr: ["lounge chicha", "moscou", "chicha", "thé", "lounge"],
      de: ["shisha lounge", "moskau", "shisha", "tee", "lounge"],
    },
  },
  {
    slug: "shibuya-izakaya-sora",
    seedOffset: 63,
    photoPool: "restaurant",
    categoryId: CATEGORY_IDS.restaurants,
    listingType: "featured",
    city: "Tokyo, Japan",
    address: "2-24-8 Dogenzaka, Shibuya City, Tokyo 150-0043",
    latitude: 35.6595,
    longitude: 139.6983,
    phone: "+81 3 5555 2210",
    contact_whatsapp: "+81355552210",
    ratingBase: 4.8,
    bookingPriceBase: 62,
    name: {
      en: "Shibuya Izakaya Sora",
      ru: "Идзакая Shibuya Sora",
      es: "Izakaya Shibuya Sora",
      pt: "Izakaya Shibuya Sora",
      fr: "Izakaya Shibuya Sora",
      de: "Shibuya Izakaya Sora",
    },
    description: {
      en: "Neon-lit izakaya near Shibuya Crossing with yakitori sets, sake flights, and counter seating until 2 a.m.",
      ru: "Неоновая идзакая у Сибуи с якитори-сетами, дегустацией саке и местами у стойки до 2 ночи.",
      es: "Izakaya iluminada junto a Shibuya Crossing con sets de yakitori, flights de sake y barra hasta las 2 a. m.",
      pt: "Izakaya com neon perto do Shibuya Crossing, sets de yakitori, provas de sake e balcão até às 2h.",
      fr: "Izakaya néon près de Shibuya Crossing, yakitori, volées de saké et comptoir jusqu'à 2 h.",
      de: "Neon-Izakaya nahe Shibuya Crossing mit Yakitori-Sets, Sake-Flights und Thekenplätzen bis 2 Uhr.",
    },
    tags: {
      en: ["restaurant", "tokyo", "izakaya", "sake", "late night"],
      ru: ["ресторан", "токио", "изакая", "саке", "ночью"],
      es: ["restaurante", "tokio", "izakaya", "sake", "madrugada"],
      pt: ["restaurante", "tóquio", "izakaya", "sake", "noite"],
      fr: ["restaurant", "tokyo", "izakaya", "saké", "tard le soir"],
      de: ["restaurant", "tokio", "izakaya", "sake", "spät abends"],
    },
  },
];
