import { StyleSheet } from "react-native";
import type { ThemeColors } from "@/shared/theme/palettes";
import type { ThemeMode } from "@/contexts/ThemeContext";
import { COMPOSER_HEIGHT, FOOTER_VERTICAL_PADDING } from "../model/constants";

export function createMessageThreadStyles(
  colors: ThemeColors,
  mode: ThemeMode,
  insetsTop: number,
  stableBottomInset: number,
) {
  return StyleSheet.create({
    root: { flex: 1, backgroundColor: colors.background },
    content: { flex: 1 },
    header: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      zIndex: 10,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      backgroundColor: colors.card,
      paddingTop: Math.max(insetsTop, 10),
      paddingHorizontal: 12,
      paddingBottom: 10,
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    backBtn: {
      width: 34,
      height: 34,
      borderRadius: 17,
      alignItems: "center",
      justifyContent: "center",
    },
    headerCenter: { flex: 1, alignItems: "center" },
    peerName: { color: colors.text, fontSize: 16, fontWeight: "700" },
    peerSeen: { color: colors.textMuted, fontSize: 12, marginTop: 2 },
    peerAvatar: { width: 36, height: 36, borderRadius: 18, backgroundColor: colors.surface },
    listContent: {
      paddingTop: Math.max(insetsTop, 10) + 62,
      paddingHorizontal: 12,
      paddingBottom: Math.max(stableBottomInset, 12) + 12,
      gap: 8,
    },
    list: { flex: 1 },
    emptyListContent: {
      flexGrow: 1,
      justifyContent: "center",
    },
    emptyWrap: {
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 20,
      gap: 10,
    },
    emptyText: { color: colors.textMuted, textAlign: "center", fontSize: 15 },
    dividerWrap: { alignItems: "center", marginVertical: 6 },
    dividerText: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: "600",
      backgroundColor: colors.card,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 4,
    },
    bubbleWrapMine: { alignItems: "flex-end" },
    bubbleWrapPeer: { alignItems: "flex-start" },
    bubble: {
      width: "80%",
      borderRadius: 14,
      paddingHorizontal: 12,
      paddingVertical: 8,
      paddingRight: 12,
      borderWidth: 0,
    },
    bubbleMine: {
      backgroundColor: mode === "dark" ? "#ff7a59" : "#ec6544",
      borderTopRightRadius: 6,
    },
    bubblePeer: {
      backgroundColor: mode === "dark" ? "#1f2230" : "#f3f6ff",
      borderTopLeftRadius: 6,
    },
    bubbleTextMine: { color: colors.onPrimary, fontSize: 15, lineHeight: 20 },
    bubbleTextPeer: { color: colors.text, fontSize: 15, lineHeight: 20 },
    bubbleAttachments: { marginTop: 8, flexDirection: "row", flexWrap: "wrap", gap: 6 },
    bubbleAttachmentImage: {
      width: 160,
      height: 160,
      borderRadius: 10,
      backgroundColor: colors.surface,
    },
    bubbleMetaRow: {
      marginTop: 4,
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
    },
    bubbleMetaRowMine: { alignSelf: "flex-end" },
    bubbleMetaRowPeer: { alignSelf: "flex-start" },
    bubbleMeta: { fontSize: 11 },
    bubbleMetaMine: { color: mode === "dark" ? "rgba(17,24,39,0.78)" : "rgba(255,255,255,0.72)" },
    bubbleMetaPeer: { color: mode === "dark" ? "rgba(255,255,255,0.52)" : "rgba(17,24,39,0.48)" },
    readIndicator: { marginTop: 0.5 },
    reactionRow: { marginTop: 5, flexDirection: "row", flexWrap: "wrap", gap: 6 },
    reactionChip: {
      borderRadius: 999,
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.background,
    },
    reactionChipActive: { borderColor: colors.primary },
    reactionText: { color: colors.text, fontSize: 12, fontWeight: "600" },
    reactionTrigger: {
      width: 28,
      height: 28,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.card,
    },
    deleteTrigger: {
      width: 28,
      height: 28,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.card,
    },
    swipeActionWrap: {
      justifyContent: "center",
      paddingHorizontal: 8,
    },
    swipeActionRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    swipeActionBtn: {
      width: 36,
      height: 36,
      borderRadius: 18,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.card,
    },
    pickerRow: { marginTop: 6, flexDirection: "row", gap: 6 },
    pickerBtn: {
      minWidth: 32,
      height: 30,
      borderRadius: 15,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.card,
      alignItems: "center",
      justifyContent: "center",
    },
    footer: {
      borderTopWidth: 1,
      borderTopColor: colors.border,
      backgroundColor: colors.card,
      paddingHorizontal: 12,
      paddingVertical: FOOTER_VERTICAL_PADDING,
      alignItems: "stretch",
      gap: 12,
    },
    stickerPanel: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 14,
      backgroundColor: colors.background,
      padding: 8,
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
    },
    stickerChip: {
      width: 46,
      height: 46,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.card,
    },
    stickerImage: { width: 28, height: 28, borderRadius: 8 },
    attachmentStrip: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
    attachmentThumbWrap: { position: "relative" },
    attachmentThumb: {
      width: 64,
      height: 64,
      borderRadius: 10,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
    },
    attachmentRemove: {
      position: "absolute",
      top: -6,
      right: -6,
      width: 20,
      height: 20,
      borderRadius: 10,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.card,
      borderWidth: 1,
      borderColor: colors.border,
    },
    composerRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    attachBtn: {
      width: COMPOSER_HEIGHT,
      height: COMPOSER_HEIGHT,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.background,
    },
    stickerBtn: {
      width: COMPOSER_HEIGHT,
      height: COMPOSER_HEIGHT,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.background,
    },
    inputWrap: { flex: 1, minWidth: 0 },
    input: {
      minHeight: COMPOSER_HEIGHT,
      maxHeight: 120,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 14,
      backgroundColor: colors.background,
      color: colors.text,
      fontSize: 15,
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    sendBtn: {
      width: COMPOSER_HEIGHT,
      height: COMPOSER_HEIGHT,
      borderRadius: 14,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.primary,
    },
  });
}

export type MessageThreadStyles = ReturnType<typeof createMessageThreadStyles>;
