export const RECOMMENDED_BATCH_SIZE = 20;
export const RECOMMENDED_ITEM_ESTIMATED_SIZE = 156;
export const CATEGORY_PILL_ESTIMATED_WIDTH = 148;
export const FEATURED_CARD_ESTIMATED_WIDTH = 168;

/** Matches `homePageStyles.pill` vertical padding + icon wrap height. */
export const HOME_CATEGORY_PILL_PADDING_VERTICAL = 10;
export const HOME_CATEGORY_PILL_ICON_SIZE = 24;
export const HOME_CATEGORY_PILL_HEIGHT =
  HOME_CATEGORY_PILL_PADDING_VERTICAL * 2 + HOME_CATEGORY_PILL_ICON_SIZE;
