import { StyleSheet } from "react-native";

export const createPostStyles = StyleSheet.create({
  createMenuBody: {
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  createStepBody: {
    flex: 1,
  },
  createOptionGrid: {
    flexDirection: "row",
    gap: 10,
  },
  createOptionCard: {
    flex: 1,
    minHeight: 124,
    borderRadius: 16,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
    paddingVertical: 14,
    gap: 12,
  },
  createOptionLabel: {
    fontSize: 16,
    fontWeight: "700",
    textAlign: "center",
  },
  createOptionHint: {
    fontSize: 14,
    textAlign: "center",
  },
  createPostModalBody: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    gap: 10,
    minHeight: 420,
  },
  postUploaderBox: {
    marginTop: 8,
    borderWidth: 1,
    borderStyle: "dashed",
    borderRadius: 14,
    minHeight: 86,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 6,
  },
  postUploaderText: {
    fontSize: 14,
    fontWeight: "600",
    textAlign: "center",
  },
  postPhotoCount: {
    fontSize: 12,
  },
  postBoostRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
  },
  postFieldLabel: {
    fontSize: 13,
    fontWeight: "700",
    marginTop: 2,
    marginBottom: 6,
  },
  postFieldLabelHint: {
    fontSize: 12,
    fontWeight: "400",
    lineHeight: 16,
  },
  postFieldHint: {
    fontSize: 12,
    marginTop: 4,
    lineHeight: 16,
  },
  postFieldError: {
    fontSize: 12,
    marginTop: 6,
    fontWeight: "600",
    lineHeight: 16,
  },
  postAddressMapsHint: {
    fontSize: 12,
    marginTop: 4,
    lineHeight: 16,
  },
  postAddressInputWrap: {
    marginTop: 6,
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderRadius: 12,
    paddingLeft: 12,
    paddingRight: 4,
    minHeight: 48,
  },
  postAddressInput: {
    flex: 1,
    minWidth: 0,
    paddingVertical: 10,
    paddingRight: 4,
    fontSize: 15,
  },
  postAddressClearBtn: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
  },
  postAddressFieldWrap: {
    position: "relative",
    zIndex: 20,
  },
  postAddressSuggestionsBox: {
    position: "absolute",
    top: "100%",
    left: 0,
    right: 0,
    marginTop: 6,
    maxHeight: 168,
    borderWidth: 1,
    borderRadius: 12,
    overflow: "hidden",
    zIndex: 40,
    elevation: 12,
  },
  postAddressSuggestionsScroll: {
    maxHeight: 168,
  },
  postAddressSuggestionsLoading: {
    paddingVertical: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  postAddressSuggestionsEmpty: {
    paddingVertical: 14,
    paddingHorizontal: 12,
    fontSize: 13,
    textAlign: "center",
  },
  postAddressSuggestionRow: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "rgba(127,127,127,0.25)",
  },
  postAddressSuggestionTitle: {
    fontSize: 14,
    fontWeight: "700",
  },
  postAddressSuggestionSubtitle: {
    marginTop: 2,
    fontSize: 12,
    lineHeight: 16,
  },
  postSelectedAddressWrap: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 10,
    minWidth: 0,
  },
  postSelectedAddressTextCol: {
    flex: 1,
    gap: 4,
  },
  postSelectedAddressLabel: {
    fontSize: 11,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  postSelectedAddressText: {
    fontSize: 14,
    lineHeight: 19,
    fontWeight: "500",
  },
  postMatchedPlacesCaption: {
    marginTop: 6,
    fontSize: 12,
    fontWeight: "600",
  },
  postNewPlaceHint: {
    marginTop: 6,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "500",
  },
  postPlacesRow: {
    gap: 10,
    paddingRight: 8,
  },
  postPlaceCard: {
    position: "relative",
    width: 158,
    borderWidth: 1,
    borderRadius: 14,
    padding: 8,
    gap: 6,
    overflow: "visible",
  },
  postPlaceCardRemoveBtn: {
    position: "absolute",
    top: -6,
    right: -6,
    width: 18,
    height: 18,
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    zIndex: 2,
  },
  postPlaceImageWrap: {
    position: "relative",
  },
  postPlaceImage: {
    width: "100%",
    height: 84,
    borderRadius: 10,
  },
  postPlaceImageFallback: {
    alignItems: "center",
    justifyContent: "center",
  },
  postPlaceRatingBadge: {
    position: "absolute",
    top: 6,
    right: 6,
    minHeight: 20,
    paddingHorizontal: 6,
    borderRadius: 999,
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
  },
  postPlaceRatingText: {
    color: "#fff",
    fontSize: 11,
    fontWeight: "700",
  },
  postPlaceCardTitle: {
    fontSize: 13,
    fontWeight: "700",
  },
  postPlaceCardAddress: {
    fontSize: 12,
    lineHeight: 16,
  },
  postPhotosList: {
    marginTop: 8,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  postPhotoItem: {
    position: "relative",
    width: 56,
    height: 56,
  },
  postPhotoThumb: {
    width: 56,
    height: 56,
    borderRadius: 10,
  },
  postPhotoRemoveBtn: {
    position: "absolute",
    top: -6,
    right: -6,
    width: 18,
    height: 18,
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  createPostBackRow: {
    marginTop: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  createPostLoadingOnlyWrap: {
    flex: 1,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  createPostLoadingWrap: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    minHeight: 24,
  },
  createPostLoadingText: {
    fontSize: 13,
    fontWeight: "600",
  },
  createFlowBackBtn: {
    minHeight: 48,
    height: 48,
    borderRadius: 12,
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    flex: 1,
  },
  createFlowBackBtnText: {
    fontSize: 13,
    fontWeight: "700",
  },
  createPostPrimaryBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
});
