import { Platform, StyleSheet } from "react-native";
import type { ThemeColors } from "@/shared/theme/palettes";

export const vibeMatchStaticStyles = StyleSheet.create({
  root: { flex: 1 },
  scroll: { padding: 16, gap: 14 },
  topRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  title: { fontSize: 22, fontWeight: "800", flex: 1 },
  subtitle: { fontSize: 13 },
  section: {
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    gap: 10,
  },
  label: { fontSize: 11, fontWeight: "700", textTransform: "uppercase" },
  input: {
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: Platform.OS === "ios" ? 12 : 8,
  },
  chipRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  chip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
  },
  chipOn: {},
  chipText: { fontSize: 13, fontWeight: "600" },
  timelineRow: { flexDirection: "row", gap: 8, flexWrap: "wrap" },
  routeTimeline: { gap: 0 },
  routeStop: {
    flexDirection: "row",
    gap: 10,
    paddingVertical: 4,
  },
  routeStopWarn: { opacity: 0.88 },
  routeLeftCol: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    paddingTop: 2,
  },
  routeRailCol: {
    width: 14,
    alignItems: "center",
    alignSelf: "stretch",
  },
  routeDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  routeLine: {
    width: 2,
    flex: 1,
    minHeight: 12,
    marginTop: 4,
    borderRadius: 1,
  },
  routeStopBody: {
    flex: 1,
    minWidth: 0,
    paddingBottom: 18,
  },
  routeStopMain: {
    flexDirection: "row",
    gap: 12,
    alignItems: "flex-start",
  },
  routeStopText: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  routeStopTimeRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 6,
  },
  routeStopTime: { fontWeight: "800", fontSize: 14 },
  routeStopActivity: { fontSize: 14, fontWeight: "600" },
  routeStopName: { fontWeight: "800", fontSize: 17, lineHeight: 22 },
  routeStopAddress: { fontSize: 12, lineHeight: 17 },
  routeStopBadges: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 6,
    marginTop: 4,
  },
  routeCategoryPill: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
  },
  routeCategoryText: { fontSize: 11, fontWeight: "700" },
  routeThumbWrap: {
    width: 80,
    height: 80,
    borderRadius: 12,
    overflow: "hidden",
    flexShrink: 0,
  },
  routeThumb: {
    width: "100%",
    height: "100%",
  },
  routeRatingBadge: {
    position: "absolute",
    right: 4,
    bottom: 4,
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 8,
  },
  routeRatingText: { fontSize: 11, fontWeight: "800", color: "#fff" },
  planCheckbox: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 2,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  planCheckboxChecked: {},
  planCheckboxDisabled: { opacity: 0.45 },
  statusPill: { alignSelf: "flex-start", paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8 },
  statusOk: {},
  statusPending: {},
  statusBad: {},
  statusText: { fontSize: 11, fontWeight: "700" },
  errorBox: { padding: 12, borderRadius: 10, borderWidth: 1 },
  errorText: { fontSize: 13 },
  selectionWarning: {
    padding: 10,
    borderRadius: 10,
    borderWidth: 1,
    marginBottom: 2,
  },
  selectionWarningText: { fontSize: 13, fontWeight: "600", lineHeight: 18 },
  creditsLimitInfo: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    padding: 12,
    borderRadius: 10,
    borderWidth: 1,
  },
  creditsLimitInfoText: { flex: 1, fontSize: 13, fontWeight: "600", lineHeight: 18 },
  emptyText: { textAlign: "center", padding: 16 },
  pickerRow: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  pickerRowText: { fontSize: 15 },
  pickerCheck: { fontWeight: "700", fontSize: 12 },
  citySearchBox: {
    marginHorizontal: 14,
    marginBottom: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 12,
    height: 44,
    borderRadius: 12,
    borderWidth: 1,
  },
  citySearchInput: {
    flex: 1,
    fontSize: 15,
    paddingVertical: 0,
  },
  countryHeader: {
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 6,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  countryHeaderText: {
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0.3,
    textTransform: "uppercase",
  },
  cityPickerEmpty: {
    paddingHorizontal: 14,
    paddingVertical: 20,
    alignItems: "center",
  },
  cityPickerEmptyText: { fontSize: 14, textAlign: "center" },
});

export function vibeMatchThemeStyles(colors: ThemeColors, topInset: number, bottomInset: number) {
  return {
    root: { backgroundColor: colors.background },
    scroll: {
      paddingTop: Math.max(12, topInset),
      paddingBottom: 32 + bottomInset,
    },
    backBtn: {
      borderColor: colors.border,
      backgroundColor: colors.card,
    },
    title: { color: colors.text },
    subtitle: { color: colors.textMuted },
    section: {
      borderColor: colors.border,
      backgroundColor: colors.card,
    },
    label: { color: colors.textMuted },
    input: {
      borderColor: colors.border,
      color: colors.text,
      backgroundColor: colors.background,
    },
    chip: {
      borderColor: colors.border,
      backgroundColor: colors.background,
    },
    chipOn: { borderColor: colors.primary, backgroundColor: colors.border },
    chipText: { color: colors.text },
    routeStopTime: { color: colors.text },
    routeStopActivity: { color: colors.textMuted },
    routeStopName: { color: colors.text },
    routeStopAddress: { color: colors.textMuted },
    routeDot: { backgroundColor: colors.accent },
    routeLine: { backgroundColor: colors.border },
    routeCategoryPill: { backgroundColor: colors.tagMuted },
    routeCategoryText: { color: colors.tagMutedText },
    routeRatingBadge: { backgroundColor: "rgba(0,0,0,0.62)" },
    planCheckbox: {
      borderColor: colors.border,
      backgroundColor: colors.card,
    },
    planCheckboxChecked: {
      borderColor: colors.accent,
      backgroundColor: colors.accent,
    },
    statusOk: { backgroundColor: colors.successSurface },
    statusPending: {
      backgroundColor: colors.card,
      borderWidth: 1,
      borderColor: colors.border,
    },
    statusBad: { backgroundColor: colors.dangerSurface },
    errorBox: {
      borderColor: colors.border,
      backgroundColor: colors.dangerSurfaceStrong,
    },
    errorText: { color: colors.danger },
    selectionWarning: {
      borderColor: colors.warningBorder,
      backgroundColor: colors.dangerSurface,
    },
    selectionWarningText: { color: colors.text },
    creditsLimitInfo: {
      borderColor: colors.primary,
      backgroundColor: colors.card,
    },
    creditsLimitInfoText: { color: colors.text },
    emptyText: { color: colors.textMuted },
    pickerRow: { borderBottomColor: colors.border },
    pickerRowText: { color: colors.text },
    pickerCheck: { color: colors.primary },
    citySearchBox: {
      borderColor: colors.border,
      backgroundColor: colors.background,
    },
    citySearchInput: { color: colors.text },
    countryHeader: {
      backgroundColor: colors.background,
      borderBottomColor: colors.border,
    },
    countryHeaderText: { color: colors.textMuted },
    cityPickerEmptyText: { color: colors.textMuted },
  } satisfies Partial<Record<keyof typeof vibeMatchStaticStyles, object>>;
}
