import { StyleSheet } from "react-native";
import type { ThemeColors } from "@/shared/theme/palettes";
import {
  SHARED_PRESSABLE_HEIGHT,
  SHARED_PRESSABLE_RADIUS,
  primaryPressableStyle,
  primaryPressableTextStyle,
} from "@/shared/theme/primaryPressable";

export function createCartStyles(colors: ThemeColors, bottomInset: number) {
  return StyleSheet.create({
    root: { flex: 1, backgroundColor: colors.background },
    header: { fontSize: 22, fontWeight: "800", paddingHorizontal: 16, marginBottom: 8, color: colors.text },
    tabs: { flexDirection: "row", marginHorizontal: 16, marginBottom: 8, gap: 8 },
    tab: { flex: 1, paddingVertical: 10, borderRadius: 10, backgroundColor: colors.border, alignItems: "center" },
    tabActive: { backgroundColor: colors.primary },
    tabText: { color: colors.text, fontWeight: "600" },
    tabTextActive: { color: colors.onPrimary, fontWeight: "700" },
    card: {
      flexDirection: "row",
      gap: 12,
      padding: 12,
      backgroundColor: colors.card,
      borderRadius: 12,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: colors.border,
    },
    thumb: { width: 64, height: 64, borderRadius: 8 },
    name: { fontWeight: "700", color: colors.text },
    meta: { fontSize: 12, color: colors.textMuted, marginTop: 4 },
    price: { marginTop: 6, fontWeight: "700", color: colors.text },
    child: { fontSize: 12, color: colors.textMuted },
    shopTitleRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      justifyContent: "space-between",
      gap: 8,
    },
    shopTitleCol: { flex: 1, minWidth: 0 },
    qtyRow: { flexDirection: "row", alignItems: "center", gap: 12, marginTop: 6 },
    qtyBtn: { fontSize: 20, fontWeight: "700", color: colors.text },
    smallBtn: {
      paddingHorizontal: 10,
      paddingVertical: 6,
      backgroundColor: colors.primary,
      borderRadius: 8,
      alignItems: "center",
    },
    smallBtnDanger: {
      paddingHorizontal: 10,
      paddingVertical: 6,
      backgroundColor: colors.danger,
      borderRadius: 8,
      alignItems: "center",
      alignSelf: "flex-start",
    },
    smallBtnText: { color: colors.onPrimary, fontSize: 12, fontWeight: "600" },
    smallBtnOutline: {
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: "transparent",
      alignItems: "center",
    },
    smallBtnOutlineText: { color: colors.text, fontSize: 12, fontWeight: "600" },
    waStatusLine: { fontSize: 12, color: colors.textMuted, lineHeight: 18 },
    dangerBtnText: { color: "#ffffff", fontSize: 12, fontWeight: "600" },
    empty: { textAlign: "center", color: colors.textMuted, marginTop: 32 },
    payBar: {
      marginTop: 16,
      padding: 16,
      paddingBottom: 16 + bottomInset,
      backgroundColor: colors.card,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
    },
    totalLabel: { fontSize: 14, color: colors.textMuted },
    totalVal: { fontSize: 20, fontWeight: "800", marginTop: 4, color: colors.text },
    payRow: { flexDirection: "row", gap: 8, marginTop: 12 },
    payRowBtn: {
      flex: 1,
      minHeight: SHARED_PRESSABLE_HEIGHT,
      borderRadius: SHARED_PRESSABLE_RADIUS,
      alignItems: "center",
      justifyContent: "center",
    },
    payBtn: {
      marginTop: 12,
      ...primaryPressableStyle,
    },
    payBtnText: primaryPressableTextStyle,
    payRowBtnPrimary: { backgroundColor: primaryPressableStyle.backgroundColor },
    payRowBtnOutline: {
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: "transparent",
    },
    payRowBtnOutlineText: { color: colors.text, fontWeight: "700" },
    deleteIconBtn: {
      padding: 10,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: "rgba(239,68,68,0.45)",
      backgroundColor: "rgba(239,68,68,0.12)",
    },
    vendorBadge: {
      alignSelf: "flex-start",
      maxWidth: "100%",
      marginTop: 4,
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.background,
    },
    vendorBadgeText: {
      fontSize: 11,
      fontWeight: "700",
      color: colors.textMuted,
    },
  });
}

export type CartScreenStyles = ReturnType<typeof createCartStyles>;
