import { useMemo } from "react";
import { StyleSheet } from "react-native";
import type { ThemeColors } from "@/shared/theme/palettes";
import {
  SHARED_PRESSABLE_HEIGHT,
  SHARED_PRESSABLE_RADIUS,
  primaryPressableStyle,
  primaryPressableTextStyle,
} from "@/shared/theme/primaryPressable";
import { mergeStaticAndThemed } from "@/shared/theme/mergeThemeStyles";
import { useThemeStyles } from "@/shared/theme/useThemeStyles";

export const aiBookingStaticStyles = StyleSheet.create({
  root: { flex: 1 },
  scroll: { padding: 16, gap: 14 },
  topRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  title: { fontSize: 24, fontWeight: "800" },
  subtitle: { marginTop: 2 },
  semanticSection: {
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    gap: 10,
  },
  stepTitle: { fontWeight: "700", fontSize: 15 },
  optionChip: {
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 6,
  },
  optionChipSelected: {},
  optionChipText: { fontWeight: "600" },
  bubble: {
    borderWidth: 1,
    borderRadius: 14,
    padding: 12,
  },
  bubbleUser: {},
  bubbleText: {},
  bubbleUserText: {},
  label: { fontSize: 11, marginBottom: 2, textTransform: "uppercase", fontWeight: "700" },
  placeCard: {
    borderWidth: 1,
    borderRadius: 12,
    padding: 10,
  },
  placeCardSelected: {},
  placeRow: { flexDirection: "row", alignItems: "center", gap: 12 },
  placeThumb: {
    width: 74,
    height: 74,
    borderRadius: 10,
  },
  placeTextCol: { flex: 1, minWidth: 0 },
  placeName: { fontWeight: "700" },
  placeMeta: { fontSize: 12, marginTop: 2 },
  calendarPanel: {
    borderRadius: 10,
    padding: 8,
    marginTop: 4,
  },
  calendarNav: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  calendarNavBtn: { padding: 8, borderRadius: 8 },
  calendarNavBtnDisabled: { opacity: 0.35 },
  calendarMonthTitle: { fontWeight: "800", fontSize: 16 },
  calendarDowRow: { flexDirection: "row", marginBottom: 4 },
  calendarDowCell: {
    flex: 1,
    textAlign: "center",
    fontSize: 11,
    fontWeight: "700",
  },
  calendarWeekRow: { flexDirection: "row", alignItems: "center" },
  calendarCell: { flex: 1, alignItems: "center", justifyContent: "center", paddingVertical: 4 },
  calendarCellDayInner: {
    minWidth: 38,
    minHeight: 38,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
  },
  calendarCellDayText: { fontSize: 15, fontWeight: "700" },
  calendarCellToday: { borderStyle: "dashed" },
  calendarCellSelected: {},
  calendarCellPast: { opacity: 0.38 },
  calendarHint: { fontSize: 12 },
  slotGrid: { gap: 8, width: "100%", alignSelf: "stretch" },
  slotGridRow: { flexDirection: "row", gap: 8, width: "100%" },
  slotChip: {
    flex: 1,
    alignItems: "center",
    borderWidth: 1,
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 4,
  },
  slotChipSelected: {},
  slotChipUnavailable: { opacity: 0.45 },
  slotText: { fontSize: 12, fontWeight: "600" },
  field: {
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 8,
  },
  fieldOnCard: {
    marginBottom: 0,
  },
  formFieldsStack: { gap: 8 },
  summaryText: { fontSize: 12, lineHeight: 16 },
  commentField: {
    minHeight: 88,
    textAlignVertical: "top",
  },
  helperText: { fontSize: 12 },
  footer: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 16,
    paddingTop: 10,
    borderTopWidth: 1,
    gap: 8,
  },
  row: { flexDirection: "row", alignItems: "center", gap: 8 },
  primaryBtn: {
    ...primaryPressableStyle,
  },
  primaryBtnDisabled: {
    opacity: 0.5,
  },
  primaryBtnBusyRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  primaryBtnText: primaryPressableTextStyle,
  inlineValidationText: { fontSize: 12 },
  secondaryBtn: {
    minHeight: SHARED_PRESSABLE_HEIGHT,
    borderRadius: SHARED_PRESSABLE_RADIUS,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  secondaryBtnText: { fontWeight: "700" },
  dropdownTrigger: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  dropdownTriggerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flex: 1,
    minWidth: 0,
    marginRight: 8,
  },
  dropdownTriggerText: { fontWeight: "600", flex: 1 },
  dropdownPlaceholder: { fontWeight: "500" },
  pickerRow: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  pickerRowText: { fontSize: 15 },
  pickerCheck: { fontWeight: "700", fontSize: 12 },
  pickerRowComingSoon: { opacity: 0.92 },
  pickerRowRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexShrink: 0,
    marginLeft: 8,
  },
  categoryComingSoonBadge: {
    borderRadius: 999,
    paddingHorizontal: 7,
    paddingVertical: 3,
  },
  categoryComingSoonBadgeText: {
    fontSize: 9,
    fontWeight: "800",
    letterSpacing: 0.2,
    textTransform: "uppercase",
  },
  pickerRowLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
    minWidth: 0,
  },
  pickerRowIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  citySearchBox: {
    marginHorizontal: 14,
    marginBottom: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 12,
    height: 44,
    borderRadius: 12,
    borderWidth: 1,
  },
  citySearchInput: {
    flex: 1,
    fontSize: 15,
    paddingVertical: 0,
  },
  countryHeader: {
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 6,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  countryHeaderText: {
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0.3,
    textTransform: "uppercase",
  },
  cityPickerEmpty: {
    paddingHorizontal: 14,
    paddingVertical: 20,
    alignItems: "center",
  },
  cityPickerEmptyText: { fontSize: 14, textAlign: "center" },
});

export function aiBookingThemeStyles(colors: ThemeColors, insets: { top: number; bottom: number }) {
  return {
    root: { backgroundColor: colors.background },
    scroll: {
      paddingTop: Math.max(12, insets.top),
      paddingBottom: 130 + insets.bottom,
    },
    backBtn: {
      borderColor: colors.border,
      backgroundColor: colors.card,
    },
    title: { color: colors.text },
    subtitle: { color: colors.textMuted },
    semanticSection: {
      borderColor: colors.border,
      backgroundColor: colors.card,
    },
    stepTitle: { color: colors.text },
    optionChip: {
      borderColor: colors.border,
      backgroundColor: colors.background,
    },
    optionChipSelected: { borderColor: colors.primary, backgroundColor: colors.border },
    optionChipText: { color: colors.text },
    bubble: {
      backgroundColor: colors.background,
      borderColor: colors.border,
    },
    bubbleUser: { backgroundColor: colors.primary, borderColor: colors.primary },
    bubbleText: { color: colors.text },
    bubbleUserText: { color: colors.onPrimary },
    label: { color: colors.textMuted },
    placeCard: {
      borderColor: colors.border,
      backgroundColor: colors.background,
    },
    placeCardSelected: { borderColor: colors.primary },
    placeThumb: { backgroundColor: colors.border },
    placeName: { color: colors.text },
    placeMeta: { color: colors.textMuted },
    calendarPanel: { backgroundColor: colors.background },
    calendarMonthTitle: { color: colors.text },
    calendarDowCell: { color: colors.textMuted },
    calendarCellDayInner: { backgroundColor: colors.background },
    calendarCellDayText: { color: colors.text },
    calendarCellToday: { borderColor: colors.border },
    calendarCellSelected: { borderColor: colors.primary, backgroundColor: colors.border },
    calendarHint: { color: colors.textMuted },
    slotChip: {
      borderColor: colors.border,
      backgroundColor: colors.background,
    },
    slotChipSelected: { borderColor: colors.primary, backgroundColor: colors.border },
    slotText: { color: colors.text },
    field: {
      borderColor: colors.border,
      color: colors.text,
      backgroundColor: colors.card,
    },
    fieldOnCard: { backgroundColor: colors.background },
    summaryText: { color: colors.textMuted },
    helperText: { color: colors.textMuted },
    footer: {
      paddingBottom: Math.max(10, insets.bottom),
      borderTopColor: colors.border,
      backgroundColor: colors.background,
    },
    inlineValidationText: { color: colors.textMuted },
    secondaryBtn: { borderColor: colors.primary },
    secondaryBtnText: { color: colors.primary },
    dropdownTrigger: {
      borderColor: colors.border,
      backgroundColor: colors.background,
    },
    dropdownTriggerText: { color: colors.text },
    dropdownPlaceholder: { color: colors.textMuted },
    pickerRow: { borderBottomColor: colors.border },
    pickerRowText: { color: colors.text },
    pickerCheck: { color: colors.primary },
    pickerRowComingSoon: { opacity: 0.92 },
    categoryComingSoonBadge: { backgroundColor: colors.notification },
    categoryComingSoonBadgeText: { color: colors.onPrimary },
    pickerRowIconWrap: {
      backgroundColor: colors.background,
      borderColor: colors.border,
    },
    citySearchBox: {
      borderColor: colors.border,
      backgroundColor: colors.background,
    },
    citySearchInput: { color: colors.text },
    countryHeader: {
      backgroundColor: colors.background,
      borderBottomColor: colors.border,
    },
    countryHeaderText: { color: colors.textMuted },
    cityPickerEmptyText: { color: colors.textMuted },
  } satisfies Partial<Record<keyof typeof aiBookingStaticStyles, object>>;
}

export type AIBookingStyles = typeof aiBookingStaticStyles;

export function useAIBookingStyles(insets: { top: number; bottom: number }) {
  const themed = useThemeStyles(
    ({ colors }) => aiBookingThemeStyles(colors, insets),
    [insets.top, insets.bottom],
  );
  return useMemo(() => mergeStaticAndThemed(aiBookingStaticStyles, themed), [themed]);
}

/** @deprecated Use useAIBookingStyles */
export function createAIBookingStyles(colors: ThemeColors, insets: { top: number; bottom: number }) {
  return mergeStaticAndThemed(aiBookingStaticStyles, aiBookingThemeStyles(colors, insets));
}
