import { StyleSheet } from "react-native";
import type { ThemeColors } from "@/shared/theme/palettes";
import {
  SHARED_PRESSABLE_HEIGHT,
  SHARED_PRESSABLE_RADIUS,
  primaryPressableStyle,
  primaryPressableTextStyle,
} from "@/shared/theme/primaryPressable";

export function createAIBookingStyles(colors: ThemeColors, insets: { top: number; bottom: number }) {
  return StyleSheet.create({
    root: { flex: 1, backgroundColor: colors.background },
    scroll: { padding: 16, paddingTop: Math.max(12, insets.top), paddingBottom: 130 + insets.bottom, gap: 14 },
    topRow: { flexDirection: "row", alignItems: "center", gap: 10 },
    backBtn: {
      width: 36,
      height: 36,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.card,
      alignItems: "center",
      justifyContent: "center",
    },
    title: { color: colors.text, fontSize: 24, fontWeight: "800" },
    subtitle: { color: colors.textMuted, marginTop: 2 },
    semanticSection: {
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.card,
      borderRadius: 12,
      padding: 12,
      gap: 10,
    },
    stepTitle: { color: colors.text, fontWeight: "700", fontSize: 15 },
    optionChip: {
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.background,
      borderRadius: 10,
      paddingHorizontal: 10,
      paddingVertical: 8,
      marginBottom: 6,
    },
    optionChipSelected: { borderColor: colors.primary, backgroundColor: colors.border },
    optionChipText: { color: colors.text, fontWeight: "600" },
    bubble: {
      backgroundColor: colors.background,
      borderColor: colors.border,
      borderWidth: 1,
      borderRadius: 14,
      padding: 12,
    },
    bubbleUser: { backgroundColor: colors.primary, borderColor: colors.primary },
    bubbleText: { color: colors.text },
    bubbleUserText: { color: colors.onPrimary },
    label: { color: colors.textMuted, fontSize: 11, marginBottom: 2, textTransform: "uppercase", fontWeight: "700" },
    placeCard: {
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.background,
      borderRadius: 12,
      padding: 10,
    },
    placeCardSelected: { borderColor: colors.primary },
    placeRow: { flexDirection: "row", alignItems: "center", gap: 12 },
    placeThumb: {
      width: 74,
      height: 74,
      borderRadius: 10,
      backgroundColor: colors.border,
    },
    placeTextCol: { flex: 1, minWidth: 0 },
    placeName: { color: colors.text, fontWeight: "700" },
    placeMeta: { color: colors.textMuted, fontSize: 12, marginTop: 2 },
    calendarPanel: {
      borderRadius: 10,
      padding: 8,
      marginTop: 4,
      backgroundColor: colors.background,
    },
    calendarNav: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 10,
    },
    calendarNavBtn: { padding: 8, borderRadius: 8 },
    calendarNavBtnDisabled: { opacity: 0.35 },
    calendarMonthTitle: { color: colors.text, fontWeight: "800", fontSize: 16 },
    calendarDowRow: { flexDirection: "row", marginBottom: 4 },
    calendarDowCell: {
      flex: 1,
      textAlign: "center",
      color: colors.textMuted,
      fontSize: 11,
      fontWeight: "700",
    },
    calendarWeekRow: { flexDirection: "row", alignItems: "center" },
    calendarCell: { flex: 1, alignItems: "center", justifyContent: "center", paddingVertical: 4 },
    calendarCellDayInner: {
      minWidth: 38,
      minHeight: 38,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: "transparent",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.background,
    },
    calendarCellDayText: { color: colors.text, fontSize: 15, fontWeight: "700" },
    calendarCellToday: { borderStyle: "dashed", borderColor: colors.border },
    calendarCellSelected: { borderColor: colors.primary, backgroundColor: colors.border },
    calendarCellPast: { opacity: 0.38 },
    calendarHint: { color: colors.textMuted, fontSize: 12 },
    slotGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
    slotChip: {
      minWidth: 76,
      alignItems: "center",
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 8,
      paddingVertical: 8,
      paddingHorizontal: 10,
      backgroundColor: colors.background,
    },
    slotChipSelected: { borderColor: colors.primary, backgroundColor: colors.border },
    slotChipUnavailable: { opacity: 0.45 },
    slotText: { color: colors.text, fontSize: 12, fontWeight: "600" },
    field: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 10,
      color: colors.text,
      backgroundColor: colors.card,
      marginBottom: 8,
    },
    fieldOnCard: {
      backgroundColor: colors.background,
      marginBottom: 0,
    },
    formFieldsStack: { gap: 8 },
    summaryText: { color: colors.textMuted, fontSize: 12, lineHeight: 16 },
    commentField: {
      minHeight: 88,
      textAlignVertical: "top",
    },
    helperText: { color: colors.textMuted, fontSize: 12 },
    footer: {
      position: "absolute",
      left: 0,
      right: 0,
      bottom: 0,
      paddingHorizontal: 16,
      paddingTop: 10,
      paddingBottom: Math.max(10, insets.bottom),
      borderTopWidth: 1,
      borderTopColor: colors.border,
      backgroundColor: colors.background,
      gap: 8,
    },
    row: { flexDirection: "row", alignItems: "center", gap: 8 },
    primaryBtn: {
      ...primaryPressableStyle,
    },
    primaryBtnDisabled: {
      opacity: 0.5,
    },
    primaryBtnText: primaryPressableTextStyle,
    inlineValidationText: { color: colors.textMuted, fontSize: 12 },
    secondaryBtn: {
      minHeight: SHARED_PRESSABLE_HEIGHT,
      borderRadius: SHARED_PRESSABLE_RADIUS,
      borderWidth: 1,
      borderColor: colors.primary,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "transparent",
    },
    secondaryBtnText: { color: colors.primary, fontWeight: "700" },
    dropdownTrigger: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 12,
      backgroundColor: colors.background,
    },
    dropdownTriggerLeft: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      flex: 1,
      minWidth: 0,
      marginRight: 8,
    },
    dropdownTriggerText: { color: colors.text, fontWeight: "600", flex: 1 },
    dropdownPlaceholder: { color: colors.textMuted, fontWeight: "500" },
    pickerRow: {
      paddingHorizontal: 14,
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    pickerRowText: { color: colors.text, fontSize: 15 },
    pickerCheck: { color: colors.primary, fontWeight: "700", fontSize: 12 },
    pickerRowLeft: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      flex: 1,
      minWidth: 0,
    },
    pickerRowIconWrap: {
      width: 28,
      height: 28,
      borderRadius: 14,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.background,
      borderWidth: 1,
      borderColor: colors.border,
    },
    citySearchBox: {
      marginHorizontal: 14,
      marginBottom: 10,
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingHorizontal: 12,
      height: 44,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.background,
    },
    citySearchInput: {
      flex: 1,
      fontSize: 15,
      color: colors.text,
      paddingVertical: 0,
    },
    countryHeader: {
      paddingHorizontal: 14,
      paddingTop: 10,
      paddingBottom: 6,
      backgroundColor: colors.background,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    countryHeaderText: {
      fontSize: 12,
      fontWeight: "800",
      color: colors.textMuted,
      letterSpacing: 0.3,
      textTransform: "uppercase",
    },
    cityPickerEmpty: {
      paddingHorizontal: 14,
      paddingVertical: 20,
      alignItems: "center",
    },
    cityPickerEmptyText: { fontSize: 14, color: colors.textMuted, textAlign: "center" },
  });
}

export type AIBookingStyles = ReturnType<typeof createAIBookingStyles>;
