import { StyleSheet } from "react-native";
import type { ThemeColors } from "@/shared/theme/palettes";
import { HOME_CATEGORY_PILL_HEIGHT } from "../model/constants";

export const homePageStaticStyles = StyleSheet.create({
  root: { flex: 1 },
  content: { padding: 14, paddingBottom: 24 },
  header: {
    minHeight: 46,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  headerLeft: { flexDirection: "row", alignItems: "center", gap: 6, zIndex: 1 },
  headerRight: { flexDirection: "row", alignItems: "center", gap: 6, zIndex: 1 },
  logo: {
    position: "absolute",
    left: 0,
    right: 0,
    textAlign: "center",
    fontSize: 24,
    fontWeight: "800",
    letterSpacing: -0.4,
    pointerEvents: "none",
  },
  sub: { fontSize: 12, marginTop: 4 },
  cityToolbarRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    marginTop: 6,
  },
  citySelector: {
    flexShrink: 1,
    maxWidth: "58%",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 9,
    borderWidth: 1,
  },
  citySelectorText: { fontSize: 12, fontWeight: "600" },
  headerActionLabel: {
    fontSize: 10,
    fontWeight: "700",
    lineHeight: 12,
    flexShrink: 1,
    minWidth: 0,
  },
  bellWrap: { position: "relative" },
  bellBadge: {
    position: "absolute",
    top: -4,
    right: -4,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    paddingHorizontal: 4,
    alignItems: "center",
    justifyContent: "center",
  },
  bellBadgeText: { fontSize: 10, fontWeight: "800" },
  aiBookingBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingLeft: 7,
    paddingRight: 6,
    paddingVertical: 4,
    minHeight: 30,
    maxWidth: 128,
    flexShrink: 1,
    minWidth: 0,
    borderRadius: 12,
    borderWidth: 1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 6,
    elevation: 5,
  },
  vibeMatchBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingLeft: 8,
    paddingRight: 7,
    paddingVertical: 5,
    minHeight: 32,
    borderRadius: 9,
    borderWidth: 1,
    flexShrink: 0,
  },
  /** Vibe Matching in city row: gradient chip; flex so it shares space with city selector. */
  vibeToolbarPressable: {
    flexShrink: 1,
    minWidth: 0,
    maxWidth: "50%",
    borderRadius: 12,
    overflow: "hidden",
    elevation: 8,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.38,
    shadowRadius: 10,
  },
  vibeToolbarGradient: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingLeft: 9,
    paddingRight: 8,
    paddingVertical: 6,
    minHeight: 32,
  },
  vibeToolbarLabel: {
    fontSize: 10,
    fontWeight: "800",
    lineHeight: 12,
    flexShrink: 1,
    minWidth: 0,
  },
  searchBtn: {
    borderWidth: 1,
    paddingHorizontal: 14,
    height: 46,
    borderRadius: 14,
    marginTop: 8,
    marginBottom: 18,
    justifyContent: "center",
  },
  searchBtnText: { fontSize: 14 },
  sectionTitle: { fontSize: 18, fontWeight: "800", marginBottom: 10, letterSpacing: -0.2 },
  sectionRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  link: { fontSize: 12, fontWeight: "600" },
  pill: {
    minHeight: HOME_CATEGORY_PILL_HEIGHT,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    marginRight: 8,
    borderWidth: 1,
    justifyContent: "center",
  },
  pillContent: { flexDirection: "row", alignItems: "center", gap: 8 },
  pillIconWrap: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  pillText: {},
  pillComingSoon: {
    opacity: 0.92,
  },
  categoryComingSoonBadge: {
    borderRadius: 999,
    paddingHorizontal: 7,
    paddingVertical: 3,
  },
  categoryComingSoonBadgeText: {
    fontSize: 9,
    fontWeight: "800",
    letterSpacing: 0.2,
    textTransform: "uppercase",
  },
  categoriesFlatList: { marginBottom: 12 },
  featuredCardWrap: { marginRight: 12 },
  recommendedListSeparator: { height: 12 },
  showMoreBtn: {
    marginTop: 4,
    marginBottom: 8,
    alignSelf: "center",
    paddingHorizontal: 18,
    height: 44,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  showMoreBtnText: { fontSize: 14, fontWeight: "700" },
  cityRow: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  cityRowText: { fontSize: 14 },
  cityCheck: { fontWeight: "700", fontSize: 12 },
  citySearchBox: {
    marginHorizontal: 14,
    marginBottom: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 12,
    height: 44,
    borderRadius: 12,
    borderWidth: 1,
  },
  citySearchInput: {
    flex: 1,
    fontSize: 15,
    paddingVertical: 0,
  },
  countryHeader: {
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 6,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  countryHeaderText: {
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0.3,
    textTransform: "uppercase",
  },
  cityPickerEmpty: {
    paddingHorizontal: 14,
    paddingVertical: 20,
    alignItems: "center",
  },
  cityPickerEmptyText: { fontSize: 14, textAlign: "center" },
});

export function homePageThemeStyles(colors: ThemeColors, isDark: boolean) {
  return {
    root: { backgroundColor: colors.background },
    logo: { color: colors.text },
    sub: { color: colors.textMuted },
    citySelector: {
      borderColor: colors.border,
      backgroundColor: colors.card,
    },
    citySelectorText: { color: colors.text },
    bellBadge: { backgroundColor: colors.primary },
    bellBadgeText: { color: colors.onPrimary },
    aiBookingBtn: {
      backgroundColor: colors.notification,
      borderColor: isDark ? "rgba(255,255,255,0.2)" : "rgba(255,255,255,0.35)",
      shadowColor: colors.notification,
      shadowOpacity: isDark ? 0.45 : 0.35,
    },
    headerActionLabel: { color: colors.onPrimary },
    vibeMatchBtn: {
      borderColor: colors.border,
      backgroundColor: colors.card,
    },
    vibeToolbarPressable: {
      shadowColor: isDark ? "#a855f7" : "#c026d3",
    },
    vibeToolbarLabel: { color: "#ffffff" },
    searchBtn: {
      backgroundColor: colors.card,
      borderColor: colors.border,
    },
    searchBtnText: { color: colors.textMuted },
    sectionTitle: { color: colors.text },
    link: { color: colors.link },
    pill: {
      backgroundColor: colors.card,
      borderColor: colors.border,
    },
    pillIconWrap: {
      backgroundColor: colors.background,
      borderColor: colors.border,
    },
    pillText: { color: colors.text },
    categoryComingSoonBadge: { backgroundColor: colors.notification },
    categoryComingSoonBadgeText: { color: colors.onPrimary },
    cityRow: { borderBottomColor: colors.border },
    cityRowText: { color: colors.text },
    cityCheck: { color: colors.primary },
    citySearchBox: {
      borderColor: colors.border,
      backgroundColor: colors.background,
    },
    citySearchInput: { color: colors.text },
    countryHeader: {
      backgroundColor: colors.background,
      borderBottomColor: colors.border,
    },
    countryHeaderText: { color: colors.textMuted },
    cityPickerEmptyText: { color: colors.textMuted },
    showMoreBtn: { backgroundColor: colors.accent },
    showMoreBtnText: { color: colors.onAccent },
  } satisfies Partial<Record<keyof typeof homePageStaticStyles, object>>;
}
