import { StyleSheet } from "react-native";
import type { ThemeColors } from "@/shared/theme/palettes";
import { radii } from "@/shared/theme/radii";
import { typography } from "@/shared/theme/typography";
import {
  FEATURED_CARD_HEIGHT,
  FEATURED_CARD_ITEM_GAP,
  FEATURED_CARD_WIDTH,
  HOME_CATEGORY_PILL_HEIGHT,
} from "../model/constants";

export const homePageStaticStyles = StyleSheet.create({
  root: { flex: 1 },
  content: { padding: 14, paddingBottom: 24 },
  header: {
    minHeight: 46,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  headerLeft: { flexDirection: "row", alignItems: "center", gap: 6, zIndex: 1 },
  headerRight: { flexDirection: "row", alignItems: "center", gap: 6, zIndex: 1 },
  logo: {
    position: "absolute",
    left: 0,
    right: 0,
    textAlign: "center",
    fontSize: typography.logo.fontSize,
    fontWeight: typography.logo.fontWeight,
    letterSpacing: -0.4,
    pointerEvents: "none",
  },
  sub: { fontSize: 12, marginTop: 4 },
  cityHeaderSelector: {
    flexShrink: 1,
    maxWidth: 128,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 9,
    borderWidth: 1,
  },
  cityHeaderSelectorText: { fontSize: 14, fontWeight: "700" },
  bellWrap: { position: "relative" },
  bellBadge: {
    position: "absolute",
    top: -4,
    right: -4,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    paddingHorizontal: 4,
    alignItems: "center",
    justifyContent: "center",
  },
  bellBadgeText: { fontSize: 10, fontWeight: "800" },
  vibeMatchBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingLeft: 8,
    paddingRight: 7,
    paddingVertical: 5,
    minHeight: 32,
    borderRadius: 9,
    borderWidth: 1,
    flexShrink: 0,
  },
  searchBtn: {
    height: 52,
    borderWidth: 1.5,
    borderRadius: radii.searchBar,
    overflow: "hidden",
    marginTop: 8,
    marginBottom: 18,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.22,
    shadowRadius: 8,
    elevation: 3,
  },
  searchBtnGradientFill: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 16,
    justifyContent: "flex-start",
  },
  searchBtnText: { fontSize: 15, flex: 1, fontWeight: "600" },
  trialBanner: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginBottom: 12,
  },
  trialBannerBadge: { flex: 1, alignSelf: "center" },
  sectionTitle: { fontSize: 18, fontWeight: "800", marginBottom: 10, letterSpacing: -0.2 },
  sectionRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  link: { fontSize: 12, fontWeight: "600" },
  pill: {
    minHeight: HOME_CATEGORY_PILL_HEIGHT,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    marginRight: 8,
    borderWidth: 1,
    justifyContent: "center",
  },
  pillContent: { flexDirection: "row", alignItems: "center", gap: 8 },
  pillIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  pillText: {},
  pillComingSoon: {
    opacity: 0.92,
  },
  categoryComingSoonBadge: {
    borderRadius: 999,
    paddingHorizontal: 7,
    paddingVertical: 3,
  },
  categoryComingSoonBadgeText: {
    fontSize: 9,
    fontWeight: "800",
    letterSpacing: 0.2,
    textTransform: "uppercase",
  },
  categoriesFlatList: { marginBottom: 12 },
  featuredList: {
    height: FEATURED_CARD_HEIGHT,
  },
  featuredEmpty: {
    height: FEATURED_CARD_HEIGHT,
    borderRadius: 16,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginBottom: 4,
  },
  featuredEmptyIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 2,
  },
  featuredEmptyTitle: {
    fontSize: 15,
    fontWeight: "700",
    letterSpacing: -0.1,
    textAlign: "center",
  },
  featuredEmptySubtitle: {
    fontSize: 13,
    textAlign: "center",
    paddingHorizontal: 24,
  },
  featuredCardWrap: {
    width: FEATURED_CARD_WIDTH,
    height: FEATURED_CARD_HEIGHT,
    marginRight: FEATURED_CARD_ITEM_GAP,
  },
  /** Included in FlashList item measurement (padding, not margin). */
  recommendedItemWrap: { paddingBottom: 12 },
  showMoreBtn: {
    marginTop: 4,
    marginBottom: 8,
    alignSelf: "center",
    paddingHorizontal: 18,
    height: 44,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  showMoreBtnText: { fontSize: 14, fontWeight: "700" },
  cityRow: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  cityRowText: { fontSize: 14 },
  cityCheck: { fontWeight: "700", fontSize: 12 },
  citySearchBox: {
    marginHorizontal: 14,
    marginBottom: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 12,
    height: 44,
    borderRadius: 12,
    borderWidth: 1,
  },
  citySearchInput: {
    flex: 1,
    fontSize: 15,
    paddingVertical: 0,
  },
  countryHeader: {
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 6,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  countryHeaderText: {
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0.3,
    textTransform: "uppercase",
  },
  cityPickerEmpty: {
    paddingHorizontal: 14,
    paddingVertical: 20,
    alignItems: "center",
  },
  cityPickerEmptyText: { fontSize: 14, textAlign: "center" },
});

export function homePageThemeStyles(colors: ThemeColors) {
  return {
    root: { backgroundColor: colors.background },
    logo: { color: colors.text },
    sub: { color: colors.textMuted },
    cityHeaderSelector: {
      borderColor: colors.border,
      backgroundColor: colors.card,
    },
    bellBadge: { backgroundColor: colors.primary },
    bellBadgeText: { color: colors.onPrimary },
    vibeMatchBtn: {
      borderColor: colors.border,
      backgroundColor: colors.card,
    },
    searchBtn: {
      borderColor: `${colors.primary}80`,
      shadowColor: colors.primary,
    },
    searchBtnText: { color: colors.text },
    sectionTitle: { color: colors.text },
    link: { color: colors.link },
    pill: {
      backgroundColor: colors.card,
      borderColor: colors.border,
    },
    pillIconWrap: {},
    pillText: { color: colors.text },
    categoryComingSoonBadge: { backgroundColor: colors.notification },
    categoryComingSoonBadgeText: { color: colors.onPrimary },
    featuredEmpty: { borderColor: colors.border, backgroundColor: colors.card },
    featuredEmptyIconWrap: { backgroundColor: `${colors.primary}18` },
    featuredEmptyTitle: { color: colors.text },
    featuredEmptySubtitle: { color: colors.textMuted },
    cityRow: { borderBottomColor: colors.border },
    cityRowText: { color: colors.text },
    cityCheck: { color: colors.primary },
    citySearchBox: {
      borderColor: colors.border,
      backgroundColor: colors.background,
    },
    citySearchInput: { color: colors.text },
    countryHeader: {
      backgroundColor: colors.background,
      borderBottomColor: colors.border,
    },
    countryHeaderText: { color: colors.textMuted },
    cityPickerEmptyText: { color: colors.textMuted },
    showMoreBtn: { backgroundColor: colors.accent },
    showMoreBtnText: { color: colors.onAccent },
  } satisfies Partial<Record<keyof typeof homePageStaticStyles, object>>;
}
