export const MAX_POST_PHOTOS = 8;
export const POST_PLACE_CARD_WIDTH = 158;
export const POST_PLACE_CARD_PADDING_X = 8;
export const POST_PLACE_IMAGE_HEIGHT = 84;
export const POST_ADDRESS_AUTOCOMPLETE_DEBOUNCE_MS = 1000;
export const POST_ADDRESS_SUGGESTIONS_MIN_HEIGHT = 120;
export const POST_ADDRESS_SUGGESTIONS_KEYBOARD_GAP = 10;
